<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:24:10
?>
<?php use_helper('I18N', 'PagerNavigation', 'sfIcon', 'Date', 'Global') ?>

<?php if (!isset($uri_options)) $uri_options = null ?>

<?php if (count($users->getResults()) == 0): ?>
  We're sorry, we couldn't find any users that match your criteria.
<?php else: ?>
<?php foreach ($users->getResults() as $user): ?>

<div class="project-listing">
	<ul class="description">
                <li class="panels" >
                        <?php echo link_to(image_tag($user->getThumbnail('large')), '@show_user_profile?user='.$user->getUuid()) ?>
                </li>
		<li class="panels" style="width:50%;">
			<h3><?php echo link_to(short_string($user->getFullName(), 55), '@show_user_profile?user='.$user->getUuid()) ?></h3>
			<?php if ($sf_user->isAuthenticated()) echo link_to(icon_tag('mail').' Message', '@compose_message?recipient='.$user->getUuid()) ?>
		</li>

		<li class="panels" style="width:30%;border-left: 1px dotted #D8D8D8;padding-left:10px;">
			<ul style="float:left;">
                          <li><?php echo __('School') ?>:</li>
                          <li><?php echo __('Dept.') ?>:</li>
                          <li><?php echo __('Type') ?></li>
                          <li><?php echo __('Joined') ?>:</li>
			</ul>
			<ul style="float:left;">
                          <li><?php echo $user->getCampus() ?></li>
                          <li><?php echo ucwords(__($user->getDepartment())) ?></li>
                          <li><?php echo ucwords(__($user->getTitle())) ?></li>
                          <li><?php echo format_date($user->getsfGuardUser()->getCreatedAt()) ?></li>
			</ul>
		</li>
	</ul>
</div>

<?php endforeach; ?>

<div id="pager-navigation">
  <?php echo pager_navigation_ajax($users, 'user/ajaxUserPager?'.$uri_options, array(
  'update' => 'pager-holder',
  'loading' => 'Element.show("indicator");',
  'complete' => 'Element.hide("indicator");')) ?>
</div>

<?php endif; ?>