<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:24:10
?>
<?php use_helper('Date', 'Number', 'I18N', 'Form', 'Javascript', 'Star', 'Global') ?>

<?php echo nav_tabs('profile', $tab, $profile); ?>

<?php use_helper('Debug', 'Javascript', 'Object', 'sfPhotoGallery', 'Lightbox') ?>

    <h2>Editing Profile</h2>
      <div style="width:60%;float:right;">
        <div class="blue-shadow"><div class="blue-title blue-content">Upload Photos</div></div>
        <div class="blue-shadow">
          <div class="blue-content">
            <?php echo photo_link_to_add('user', $profile->getId(), array('modalbox' =>'true', 'label' => icon_tag('add').' Add a photo')) ?><?php //echo photo_lightbox_slideshow('user', $profile->getId()) ?><span id="photo_indicator" style="display:none;"><?php echo image_tag('indicator.gif') ?>Setting profile photo...</span>
            <table>
              <tbody>
                <?php $counter = 0; ?>
                <?php foreach(photo_get_photos('user', $profile->getId()) as $photo): ?>
                  <?php if ($counter == 0) echo "<tr>" ?>
                  <td>
                    <div style="padding: 3px; margin: 3px;" id="photo_<?php echo $photo->getUuid() ?>">
                    <?php echo light_image('/'.sfConfig::get('sf_upload_dir_name').'/thumbnails/medium/'.$photo->getRealName(), '/'.sfConfig::get('sf_upload_dir_name').'/photos/'.$photo->getRealName(), array()) ?><br />
                    <?php echo link_to(icon_tag('accept').__(' Set as profile'), 'user/setProfilePhoto?photo='.$photo->getUuid()) ?><br />
                    <?php echo link_to(icon_tag('remove').' '.__('Delete'), 'user/removePhoto?photo='.$photo->getUuid()) ?>
                    </div>
                  </td>
                  <?php $counter++; ?>
                  <?php if ($counter == 3) { $counter = 0; echo "</tr>"; } ?>
                <?php endforeach; ?>
                </tr>
              </tbody>
            </table>
            <hr class="clear" />
          </div>
        </div>
      </div>


  <div class="form-holder-blue" style="width:35%;">
    <div class="blue-shadow"><div class="blue-title blue-content" >Personal Information</div></div>

    <div class="blue-shadow">
      <?php echo form_tag('user/updateProfile', array('name' => 'profile', 'class' => 'blue',)) ?>
        <?php echo label_for('departments', __('Department'), array('style' => 'display:block;')), select_tag_departments('departments', $profile->getDepartment()->getUuid(), array('style' => 'width:50%;') ) ?><?php if ($sf_request->hasError('department')) { echo '<span class="form-error">'.$sf_request->getError('department').'</span>'; } ?><br />
        <?php echo label_for('subdepartment', __('Subdepartment/Specialty'), array('style' => 'display:block;')), input_auto_complete_tag('subdepartment',$profile->getSubdepartment(),'user/autoSubdepartmentComplete','', array('use_style' => 'true', 'style' => 'width:50%')); ?><?php if ($sf_request->hasError('subdepartment')) { echo '<span class="form-error">'.$sf_request->getError('subdepartment').'</span>'; } ?><br />
        <?php echo label_for('gender', 'Gender'), select_tag('gender', options_for_select(array(sfConfig::get('app_profile_gender_male') => 'Gentleman', sfConfig::get('app_profile_gender_female') => 'Lady'), $profile->getGender())) ?><br />

        <?php $contact = $profile->getPrimaryContactInfo() ?>
        <?php echo label_for('email', __('Email')), object_input_tag($contact, 'getEmail') ?><?php if ($sf_request->hasError('email')) { echo '<span class="form-error">'.$sf_request->getError('email').'</span>'; }?><br />
        <?php echo label_for('phone', __('Phone')), object_input_tag($contact, 'getPhone') ?><?php if ($sf_request->hasError('phone')) { echo '<span class="form-error">'.$sf_request->getError('phone').'</span>'; }?><br />
	<?php echo label_for('language', __('Language')), select_tag_languages('language', $sf_user->getCulture()) ?>
        <hr />
        <?php if ($sf_request->hasError('profile_password') || $sf_request->hasError('profile_password_confirm')) { echo '<span class="form-error">'.$sf_request->getError('profile_password').'</span>'.'<span class="form-error">'.$sf_request->getError('profile_password_confirm').'</span>'; }?>
        <?php echo label_for('profile_password', __('Password')), input_password_tag('profile_password') ?><br />
        <?php echo label_for('profile_password_confirm', __('Confirm Password')), input_password_tag('profile_password_confirm') ?><br />
        <hr />
        <?php echo label_for('about', __('A bit about yourself')), textarea_tag('about', $profile->getAbout()) ?><br />
        <?php echo submit_tag(__('Save Changes'), array('class' => 'btn', 'style' => 'margin-top:6px;')) ?>
      </form>
    </div>
  </div>       

  <hr class="clear" />

  <div class="form-holder-blue" style="width:35%;">
    <div class="blue-shadow"><div class="blue-title blue-content" >External Services</div></div>

    <div class="blue-shadow" id="external_services">
      <?php if (true) echo include_partial('user/editExternalServices',  array('profile' => $profile)); ?>
      </form>
    </div>
  </div>


  <?php /*
  <div id="privacy-settings">
    <?php echo label_for('privacy', __('privacy level')) ?><br />
    <?php echo radiobutton_tag('privacy[]', '1', $profile->checkPrivacyLevel(1)) ?> - High (Only projects or people you've joined/corresponded with)<br />
    <?php echo radiobutton_tag('privacy[]', '2', $profile->checkPrivacyLevel(2)) ?> - Medium (Anyone from your campus can contact you, see your picture)<br />
    <?php echo radiobutton_tag('privacy[]', '3', $profile->checkPrivacyLevel(3)) ?> - Low (Anyone on Cothink can see you)<br />
  </div>
  <?php echo submit_tag('update profile', array()) ?>
  </form>
        */ ?>

    <?php if (false) echo include_partial('user/editContact',  array('profile' => $profile)); ?>
    <?php if (false) echo include_partial('user/editPhoto',    array('profile' => $profile)); ?>
  <?php /*
  <div class="project-titlebar">User Contacts</div>
  <?php include_partial('user_contacts', array('user' => $profile)) ?>
  <hr />
  */ ?>
<hr class="clear" />