<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:24:10
?>
<?php use_helper('I18N', 'Global') ?>

<?php echo nav_tabs('members', $tab) ?>

  <h1><?php echo format_number_choice ('[0]0 Members|[1]1 Member|(1,+Inf]%1% Members', array('%1%' => $users->getNbResults()), $users->getNbResults()) ?></h1>
  <?php include_partial('list_filter') ?>
<div id="pager-holder">
  <?php //echo include_partial('user_pager', array('users' => $users)); ?>
</div>
