<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:24:10
?>
<?php use_helper('Debug') ?>
<div>
  Thank you for registering! You should receive a confirmation email at <?php echo urldecode($user) ?> with a link to activate your account shortly, usually within 2-3 hours. You will be able to actively participate in the cothink community as soon as you have confirmed your email.
</div>