rendering: ~
web_debug: ~
security: { class: sfGuardBasicSecurityFilter }
rembmer: { class: rememberFilter }

# generally, you will want to insert your own filters here

cache:     ~
common:    ~
flash:     ~
execution: ~
