default:
  http_metas:
    content-type: text/html

  metas:
    title:        CoThink
    robots:       index, follow
    description:  CoThink is a place where professors and students can come together with their communities to manage projects for the betterment of the world - or at least grades.
    keywords:     community service, service learning, learning, programming, project management
    language:     en

  stylesheets:    [main]

  javascripts:    [/sfPrototypePlugin/js/prototype.js]

  has_layout:     on
  layout:         layout
