<?php
// auto-generated by sfPropelCrud
// date: 2008/06/07 23:07:24
?>
<?php use_helper('Javascript', 'Date', 'sfIcon', 'I18N', 'nifty') ?>
  <div class="vote-marker" id="mark_<?php echo $feature->getUuid() ?>">
    <span ><strong><?php echo format_number_choice('[0]0 Votes|[1]1 Vote|[2,+Inf] %1% votes', array('%1%' => $feature->getRecommendationScore()), $feature->getRecommendationScore()) ?></strong></span><br />
    <p class="vote-marker-link" style="background-color: white;color: green;">
    <?php
    if ($feature->isOpen())
    {
      if ($sf_user->isAuthenticated())
      {
        if ($feature->userRecommendationExists($sf_user->getId()))
        {
          // already interested
          echo 'Voted!';
        }
        else
        {
          // didn't declare interest yet
          echo link_to_remote('Vote?', array(
            'url'      => 'features/vote?feature='.$feature->getUuid(),
            'update'   => array('success' => 'mark_holder_'.$feature->getUuid()),
            'loading'  => "Element.show('indicator_".$feature->getUuid()."')",
            'complete' => "Element.hide('indicator_".$feature->getUuid()."');".visual_effect('highlight', 'mark_'.$feature->getUuid()),
          ));
        }
      }
      else
      {
        echo link_to_function(__('Login to vote'), visual_effect("toggle_appear", "sf_guard_auth_form"));
      }
    }
    else
    {
      echo format_number_choice('['.sfConfig::get('app_feature_status_closed').']Closed!|['.sfConfig::get('app_feature_status_implemented').']Done!|['.sfConfig::get('app_feature_status_fixed').',+Inf]Fixed!', array('%1%' => $feature->getStatus()), $feature->getStatus());
    }
    ?>
    </p>
  </div>
  
  <?php echo javascript_tag(nifty_round_elements( "mark_".$feature->getUuid(), "all 5px" ) ) ?>