<?php
// auto-generated by sfPropelCrud
// date: 2008/06/07 23:07:24
?>
<?php use_helper('Object', 'Validation') ?>

  <?php echo form_tag('features/saveNew') ?>
  
  <?php echo input_hidden_tag('referer',$sf_request->getReferer()) ?>

  <?php echo label_for('type', __('What do you want us to know about?'), array('style' => 'display:block;')),
  select_tag('type', options_for_select(array(
                                        sfConfig::get('app_feature_type_bug') => __('A Bug Report'),
                                        sfConfig::get('app_feature_type_feature') => __('A Feature Request')
                                        ))) ?>

  <?php echo label_for('type', __('What category is this in?'), array('style' => 'display:block;')),
  select_tag('category', options_for_select(array(
                                        sfConfig::get('app_feature_category_other')     => __('Other'),
                                        sfConfig::get('app_feature_category_design')    => __('Design'),
                                        sfConfig::get('app_feature_category_projects')  => __('Projects'),
                                        sfConfig::get('app_feature_category_inbox')     => __('Inbox'),
                                        ))) ?>
                                        
<?php echo label_for('title', __('What do you call your feature, or what is the bug?').'<span class=form-error>'.__(form_error('title')).'</span>', array('style' => 'display:block;')), object_input_tag($feature, 'getTitle') ?>
    <?php echo label_for('description', __('Describe it in depth').'<span class=form-error>'.__(form_error('description')).'</span>', array('style' => 'display:block;')), object_textarea_tag($feature, 'getDescription', array (
    'size' => '30x3',
  )) ?>
  <?php echo submit_tag('save', array('class' => 'btn')) ?>
  </form>