<?php
// auto-generated by sfPropelCrud
// date: 2008/06/07 23:07:24
?>
<?php use_helper('Object') ?>

<?php echo form_tag('features/update') ?>

<?php echo object_input_hidden_tag($suggested_feature, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Uuid:</th>
  <td><?php echo object_input_tag($suggested_feature, 'getUuid', array (
  'size' => 36,
)) ?></td>
</tr>
<tr>
  <th>User*:</th>
  <td><?php echo object_select_tag($suggested_feature, 'getUserId', array (
  'related_class' => 'sfGuardUser',
)) ?></td>
</tr>
<tr>
  <th>Title:</th>
  <td><?php echo object_textarea_tag($suggested_feature, 'getTitle', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Slug*:</th>
  <td><?php echo object_input_tag($suggested_feature, 'getSlug', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Description:</th>
  <td><?php echo object_textarea_tag($suggested_feature, 'getDescription', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Status:</th>
  <td><?php echo object_input_tag($suggested_feature, 'getStatus', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Type:</th>
  <td><?php echo object_input_tag($suggested_feature, 'getType', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Feeling:</th>
  <td><?php echo object_input_tag($suggested_feature, 'getFeeling', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Deleted at:</th>
  <td><?php echo object_input_date_tag($suggested_feature, 'getDeletedAt', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($suggested_feature->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'features/delete?id='.$suggested_feature->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'features/show?id='.$suggested_feature->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'features/list') ?>
<?php endif; ?>
</form>
