<?php
// auto-generated by sfPropelCrud
// date: 2008/06/07 23:07:24
?>
<?php use_helper('Javascript', 'Date', 'sfIcon', 'Global', 'Object') ?>

<?php $tab = $sf_params->get('tab') ?>
<?php if (!isset($tab)): ?>
  <?php $tab = 'mostrecent'; ?>
<?php endif; ?>
	<?php echo nav_tabs('features', $tab); ?>

<?php if ($sf_user->isAuthenticated()): ?>
<?php echo link_to_function('Hide Suggestion Form', visual_effect('toggle_blind', 'new_feature', array("duration" => .5))) ?>
<?php $new_feature = new SuggestedFeature() ?>
<div id="new_feature">
  <div class="blue-shadow"><div class="blue-title blue-content">Tell us what's up!</div></div>
  <div class="blue-shadow">
    <div class="blue-content">
      <?php echo form_tag('features/saveNew') ?>
      
      <?php echo label_for('type', __('What do you want us to know about?'), array('style' => 'display:block;')),
      select_tag('type', options_for_select(array(
                                            sfConfig::get('app_feature_type_bug') => __('A Bug Report'),
                                            sfConfig::get('app_feature_type_feature') => __('A Feature Request')
                                            ))) ?>

  <?php echo label_for('type', __('What category is this in?'), array('style' => 'display:block;')),
  select_tag('category', options_for_select(array(
                                        sfConfig::get('app_feature_category_other')     => __('Other'),
                                        sfConfig::get('app_feature_category_design')    => __('Design'),
                                        sfConfig::get('app_feature_category_projects')  => __('Projects'),
                                        sfConfig::get('app_feature_category_inbox')     => __('Inbox'),
                                        ))) ?>
     
      <?php echo label_for('title', __('What do you call your feature?'), array('style' => 'display:block;')), object_input_tag($new_feature, 'getTitle', array (
        'size' => '30x3',
        'style' => 'border:1px solid black;'
      )) ?>
        <?php echo label_for('description', __('Describe your feature in depth'), array('style' => 'display:block;')), object_textarea_tag($new_feature, 'getDescription', array (
        'size' => '30x3',
      )) ?>
      <?php echo submit_tag('save', array('class' => 'btn')) ?>
      </form>
    </div>
  </div>
</div>
<?php endif; ?>
<?php foreach ($features as $feature): ?>
<div class="suggested-feature" id="feature_<?php echo $feature->getUuid() ?>" style="clear:left;padding:10px 0px;">
  <div id="mark_holder_<?php echo $feature->getUuid() ?>" style="float:left;">
    <?php include_partial('features/feature_votes', array('feature' => $feature)) ?>
  </div>
  <div style="float:left;max-width:80%;">
    <h3><?php echo link_to($feature->getId().'. '.$feature->getTitle(), 'features/show?feature='.$feature->getUuid(), array('id' => $feature->getId())) ?> (<?php echo format_number_choice('['.sfConfig::get('app_feature_status_closed').']Closed|['.sfConfig::get('app_feature_status_open').']Open|['.sfConfig::get('app_feature_status_implemented').']Implemented|['.sfConfig::get('app_feature_status_fixed').']Fixed', array('%1%' => $feature->getStatus()), $feature->getStatus()) ?>)<span id="indicator_<?php echo $feature->getUuid() ?>" style="display:none;"><?php echo image_tag('indicator.gif') ?> Casting Vote...</span></h3>
    <h4><?php echo __('A %type% Suggested by %1% %2% ago, regarding %category%',
                      array('%1%' => link_to($feature->getsfGuardUser()->getProfile(), '@show_user?user='.$feature->getsfGuardUser()->getProfile()->GetUuid()),
                            '%2%' => distance_of_time_in_words($feature->getCreatedAt('U')),
                            '%type%' => format_number_choice('['.sfConfig::get('app_feature_type_bug').']Bug Report|['.sfConfig::get('app_feature_type_feature').']Feature Request', array(), $feature->getType()),
                            '%category%' => $feature->getCategoryInWords())) ?></h4>
    <p><?php echo $feature->getDescription() ?></p>
  </div>
  <hr class="clear" />
</div>
<?php endforeach; ?>
<hr class="clear" />

