<?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Tags', 'Javascript', 'sfIcon') ?>
<div id="project-positions-search">
	<?php //echo link_to_function('Filter Projects', visual_effect('toggle_blind', 'project-filter-criteria', array("duration" => .5))) ?>
	<div id="project-filter-criteria" style="display:;">
	<?php echo form_remote_tag(array(
              'update' => 'pager-holder',
              'url'    => 'project/ajaxProjectPager',
              'loading'  => "Element.show('form-search-indicator')",
              'complete' => "Element.hide('form-search-indicator');".visual_effect('highlight', 'pager-holder'),
              )) ?>
	<ul>
		<?php //<li><?php echo label_for('project_owner', 'Owner'), input_auto_complete_tag('project_owner','','project/autoComplete?field=owner','','use_style=true') </li> ?>
		<li><?php echo label_for('project_title', 'Title'), input_auto_complete_tag('project_title','','project/autoComplete?field=title','','use_style=true') ?></li>
		<li><?php echo label_for('project_school', 'School'), select_tag('project_school', objects_for_select($campuses, 'getId', 'getName', '', array('include_blank' => true, ))) ?></li>
		<?php /*<li><?php echo label_for('project_status', 'Status'), select_tag('project_status', options_for_select(array(
                        '' => '',
                        '0' => __('complete'),
                        '1' => __('cancelled'),
                        '2' => __('pending approval'),
                        '3' => __('in progress'),
                        '4' => __('unknown'),
                        )) )
        ?></li> */ ?>
		<li><?php echo label_for('project_department', 'Department'), select_tag('project_department', objects_for_select($departments, 'getId', 'getName', '', array('include_blank'=>true)), array('class'=>'xxx')) ?></li>
		<li><br /><?php echo submit_tag(__('Update Projects')) ?></li>
	</ul>
	</form>

	<div style="height:20px;display:inline;">
      <p id="form-search-indicator" style="display:none">
      	<?php echo image_tag('indicator.gif') ?> Searching projects...
      </p>
	</div>
	</div>
</div>