  <?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Object', 'Global', 'Project') ?>
  <h1>General Information</h1>
        <div class="blue-content">
            Project: <strong><?php echo $project->getTitle() ?></strong><br />
            Department: <?php echo $project->getDepartment()?>, Campus: <?php echo $project->getCampus() ?><br />
            Description: <?php echo $project->getDescription() ?><br />
            Notes: <?php echo $project->getNotes() ?><br />
            Tag: <?php echo $project->getTagsAsText() ?><br />
            Community Benefits: <?php echo $project->getCommunityBenefits() ?><br />
            Why it's good for students:<br /><?php echo $project->getStudentReasons() ?><br />
        </div>
