  <?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Object', 'Global', 'Project') ?>
  <h1>Timeline</h1>
        <div class="blue-content">
            Roughly, how long should the project take to complete? <strong><?php echo $project->getLengthInWords() ?></strong><br />
            Do you prefer students on any term length? <strong><?php echo $project->getPreferredTermLengthInWords() ?></strong><br />
        </div>
