<?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Date', 'Number', 'I18N', 'Global') ?>
<?php $tab = $sf_params->get('tab') ?>
<?php if (!isset($tab)) $tab = 'team' ?>
  <div id="project-tabs">
    <ul>
	<?php echo nav_tabs('project', $tab, $project); ?>
    </ul>
  </div>
  
  <div style="border: 1px solid #72BE44;background-color: #D9E1FF;padding: 4px;margin-bottom: 10px;">
      Your application has been sent, and will be reviewed along with your message. Thank you for your interest in "<em><?php echo $position->getProject()->getTitle() ?></em>" 
  </div>
