  <?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Object', 'Global', 'Project', 'Form') ?>

<?php include_partial("home/storage_div")?>

<?php echo nav_tabs('projects', $tab); ?>

  <?php if ($sf_user->isAuthenticated() && $project->getOwnerId() == $sf_user->getId()): ?>
    <?php echo include_partial('project/page2Form', array('project' => $project, )); ?>
  <?php else: ?>
    <?php echo include_partial('project/page2Review', array('project' => $project, )); ?>
  <?php endif; ?>

  <div id="comments">
    <h3>Community feedback on this page of your application</h3>
    <?php if ($project->getFlaggedHelp()): ?>
      <?php include_component('sfComment', 'commentList', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page2')); ?>
      <?php include_component('sfComment', 'commentForm', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page2')); ?>
    <?php else: ?>
    You haven't requested any feedback. Feel free to ask though, everyone's way nice!
    <?php endif; ?>
  </div>
  
  <hr class="clear" />