  <?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Object', 'Global', 'Project') ?>

<?php include_partial("home/storage_div")?>

<?php $tab = $sf_params->get('tab') ?>
<?php if (!isset($tab)) $tab = 'create' ?>
  <div id="project-tabs">
    <ul>
	<?php echo nav_tabs('projects', $tab); ?>
    </ul>
  </div>

  <h1>We love to help!</h1>
  <div id="project-information" style="background-color:#87B94D;color:white;padding:4px;">
    <?php echo form_tag('@flag_project_application_for_help', array()) ?>
      <?php echo input_hidden_tag('id', $project->getUuid(), array()) ?>
      <?php if ($sf_request->hasError('regarding')) { echo '<span class="form-error">'.$sf_request->getError('regarding').'</span>'; } ?><br />
      <?php echo label_for('regarding', 'What area would you like us to help with?'), input_tag('regarding', '', array()) ?>
      <?php if ($sf_request->hasError('details')) { echo '<span class="form-error">'.$sf_request->getError('details').'</span>'; } ?><br />
      <?php echo label_for('details', 'Describe your question in depth'), textarea_tag('details') ?>
      
      <?php if ($sf_request->hasError('party')) { echo '<span class="form-error">'.$sf_request->getError('party').'</span>'; } ?><br />
      <?php echo label_for('party', 'Who would you like to give you assistance?'), select_tag('party', options_for_select(array(sfConfig::get('app_project_application_advice_public') => 'The Cothink community (Public, access to huge group of experts)', sfConfig::get('app_project_application_advice_cothink') => 'Cothink staff (highly confidential, takes longer)', ), sfConfig::get('app_project_application_advice_public'))) ?>
      
      <?php echo submit_tag('Submit for community help', array()) ?>
      
    </form>
  </div>
  
  <hr class="clear" />