<?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Tags', 'Object', 'Global', 'I18N') ?>

<?php $tab = $sf_params->get('tab') ?>
<?php if (!isset($tab)): ?>
  <?php $tab = 'myprojects'; ?>
<?php endif; ?>

<?php echo nav_tabs('projects', $tab); ?>

<?php $applications = $sf_user->getProfile()->getProjectApplications() ?> 

<?php if (count($applications) > 0): ?>
  <h2><?php echo format_number_choice ('[0]0 Project applications|[1]1 Project application|(1,+Inf]%1% Project applications', array('%1%' => count($applications)), count($applications)) ?></h2>
  <?php foreach ($applications as $project): ?>
    <div class="project-listing">
    	<ul class="description">
                    <li class="panels" >
                            <?php echo link_to('<img alt="Noproject" src="/cothink/web/uploads/thumbnails/small/noproject.png"/>', 'project/show?slug='.$project->getSlug()) ?>
                    </li>
    		<li class="panels" style="width:55%;">
    			<h3><?php echo link_to(short_string($project->getTitle(), 55), '@show_project_application?id='.$project->getUuid()) ?></h3>
    			<?php echo short_string($project->getDescription(), 100) ?><br />
    			<?php echo link_to('Delete Application', '@remove_project_application?id='.$project->getUuid(), 'post=true&confirm=Are you sure you want to delete the application "'.$project->getTitle().'"?') ?> | <?php echo link_to('Get some help on this application', '@flag_project_application_for_help?id='.$project->getUuid()) ?> | <?php echo link_to('Preview', '@create_project_preview?id='.$project->getUuid()) ?>
    		</li>

    		<li class="panels" style="width:30%;border-left: 1px dotted #D8D8D8;padding-left:10px;">
    			<ul style="float:left;">
    				<li><?php echo __('Complete') ?>:</li>
    				<li><?php echo __('Dept') ?>:</li>
    				<li><?php echo __('Status') ?>:</li>
    			</ul>
    			<ul style="float:left;">
    			  <li><?php echo $project->getPercentComplete() ?>%</li>
    				<li><?php echo ucwords(__($project->getDepartment())) ?></li>
    				<li><?php echo ucwords($project->getStatusInWords()) ?></li>
    			</ul>
    		</li>
    	</ul>
    </div>
  <?php endforeach ?>
<?php endif ?>
<hr class="clear" />
<h2><?php echo format_number_choice ('[0]0 Projects you\'re involved in|[1]1 Project you\'re involved in|(1,+Inf]%1% Projects you\'re involved in', array('%1%' => $projects->getNbResults()), $projects->getNbResults()) ?></h2>
<?php if ($projects->getNbResults() == 0): ?>
  <div id="pager-holder">Sorry, no results found for your search</div>
<?php else: ?>
<?php echo include_component('project', 'listFilter'); ?>
<div id="pager-holder">
  <?php echo include_partial('project_pager', array('projects' => $projects, 'tab' => $tab)); ?>
</div>
<?php endif; ?>
<?php //echo link_to (ucwords(__('create a new project')), 'project/create') ?>
