<?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Date', 'Number', 'I18N', 'Global', 'Star') ?>

  <div class="project-titlebar">
    <h3 style="display:inline;"><?php echo ucwords(__('details for "%title%"', array("%title%" => $project->getTitle()))) ?></h3> 
    <?php if ($sf_user->isAuthenticated() && $project->isAdmin($sf_user->getGuardUser()))
    {
      echo '('.link_to(__('click here to edit project'), 'project/edit?slug='.$project->getSlug()).')';
    }
    ?>
    </div>
  <div style="padding:4px" id="project-details">
    <?php if ($sf_user->isAuthenticated()): ?>
      
    
    <span>Mark as favorite (<?php echo link_to_star($project, array('txt_on' => 'true')) ?>)</span>

    <?php endif ?>  
    <div><?php echo __("this project is owned by %owner% of %school%", array("%owner%" => $project->getOwner(), "%school%"  => $project->getOwner()->getCampus())) ?></div>
    <div><?php echo __("it begins on %1% and ends on %2%", array("%1%" => format_date($project->getBegin()), "%2%" => format_date($project->getFinish()))) ?></div>
    
    <div style="border: 1px solid black;padding:4px;"><span><?php echo ucwords(__('description')) ?>: </span><p style="padding:4px;"><?php echo nl2br($project->getDescription()) ?><br /><strong><?php echo $project->getUuid() ?></strong></p></div>
    <div><span><?php echo ucwords(__('tags')).' ('.__('keywords').')' ?>: </span><?php echo tags_to_links($project->getTagsAsArray()) ?></div>
    <div><?php include_partial('status', array('project' => $project)) ?></div>
    <?php //<div><span>Scale: </span><?php echo format_number_choice('[0]small|[1]medium|[2]large|(2,+Inf]Unknown scale code', '', $project->getScale()) </div> ?>
  </div>

  <div><?php include_partial('positions', array('project' => $project)) ?></div>
  <div><?php include_partial('project_tasklist', array('project' => $project)) ?></div>
  
  <?php echo link_to_function(ucwords(__('comments for %1%', array('%1%' => $project->getTitle()))), visual_effect('toggle_blind', 'comments-holder', array('duration' => 0.5)), array('class' => 'titlebar-clickable project-titlebar')); ?>
  <div id='comments-holder' class='collapsed' style='padding:4px;'>
    <h3><?php echo ucwords(__('comments')) ?></h3>
    <?php
      include_component('sfComment', 'commentList', array('object' => $project));
      include_component('sfComment', 'commentForm', array('object' => $project));
    ?>
  </div>
