  <?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
?>
<?php use_helper('Object', 'Global', 'Project') ?>

<?php include_partial("home/storage_div")?>

<?php echo nav_tabs('projects', $tab); ?>

<h1>Preview your project . . .</h1>

<hr />
<?php echo include_partial('project/page1Review', array('project' => $project, )); ?>

<?php echo link_to_function('Page 1 comments >>', visual_effect('toggle_blind', 'page1-comments')) ?>
<div id="page1-comments" style="display:none;">
  <h3>Community feedback on this page of your application</h3>
  <?php if ($project->getFlaggedHelp()): ?>
    <?php include_component('sfComment', 'commentList', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page1')); ?>
    <?php include_component('sfComment', 'commentForm', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page1')); ?>
  <?php else: ?>
  You haven't requested any feedback. Feel free to ask though, everyone's way nice!
  <?php endif; ?>
</div>

<?php echo include_partial('project/page2Review', array('project' => $project, )); ?>

<?php echo link_to_function('Page 2 comments >>', visual_effect('toggle_blind', 'page2-comments')) ?>
<div id="page2-comments" style="display:none;">
  <h3>Community feedback on this page of your application</h3>
  <?php if ($project->getFlaggedHelp()): ?>
    <?php include_component('sfComment', 'commentList', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page2')); ?>
    <?php include_component('sfComment', 'commentForm', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page2')); ?>
  <?php else: ?>
  You haven't requested any feedback. Feel free to ask though, everyone's way nice!
  <?php endif; ?>
</div>

<?php echo include_partial('project/page3Review', array('project' => $project, )); ?>

<?php echo link_to_function('Page 3 comments >>', visual_effect('toggle_blind', 'page3-comments')) ?>
<div id="page3-comments" style="display:none;">
  <h3>Community feedback on this page of your application</h3>
  <?php if ($project->getFlaggedHelp()): ?>
    <?php include_component('sfComment', 'commentList', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page3')); ?>
    <?php include_component('sfComment', 'commentForm', array('object' => $project, 'namespace' => 'projectapp_'.$project->getId().'_page3')); ?>
  <?php else: ?>
  You haven't requested any feedback. Feel free to ask though, everyone's way nice!
  <?php endif; ?>
</div>


