  <?php
// auto-generated by sfPropelCrud
// date: 2008/04/03 03:08:20
// it works I think - it does work it really does, but does the page update?
?>
<?php use_helper('Object', 'Global', 'Project', 'Form') ?>

<?php include_partial("home/storage_div")?>

<?php $tab = $sf_params->get('tab') ?>
<?php if (!isset($tab)) $tab = 'create' ?>

<?php echo nav_tabs('projects', $tab); ?>

<h1>hmm</h1>

  <?php if ($sf_user->isAuthenticated() && $project_app->getOwnerId() == $sf_user->getId()): ?>
    <?php echo include_partial('project/page2Form', array('project' => $project_app, )); ?>
  <?php else: ?>
    <?php echo include_partial('project/page2Review', array('project' => $project_app, )); ?>
  <?php endif; ?>

  <div id="comments">
    <h3>Community feedback on this page of your application</h3>
    <?php if ($project_app->getFlaggedHelp()): ?>
      <?php include_component('sfComment', 'commentList', array('object' => $project_app, 'namespace' => 'projectapp_'.$project_app->getId().'_page2')); ?>
      <?php include_component('sfComment', 'commentForm', array('object' => $project_app, 'namespace' => 'projectapp_'.$project_app->getId().'_page2')); ?>
    <?php else: ?>
    You haven't requested any feedback. Feel free to ask though, everyone's way nice!
    <?php endif; ?>
  </div>
  
  <hr class="clear" />