<?php
// auto-generated by sfPropelCrud
// date: 2008/04/07 23:35:01
?>
<?php use_helper('Object', 'Global') ?>

<?php echo nav_tabs('project', 'tasks', $task->getProject()); ?>
  
<div id="form-holder-blue" style="margin-bottom:10px;margin-top:25px;float:none;" class="form-holder-blue">
  <div class="blue-shadow"><div class="blue-title blue-content">Edit task for your project</div></div>
  <div class="blue-shadow">
    <div class="blue-content">
      <?php echo form_tag('tasks/update') ?>
        <fieldset id="task-details" style="vertical-align:top;">
          <?php echo input_hidden_tag('task', $task->getUuid(), array()) ?>
          <ul>
            <li style="float:left;width:50%;margin-right:5px;">
                <?php echo label_for('name', 'Task Name'), object_input_tag($task, 'getName', array('style' => 'width:100%;'))?><br />
            </li>
            <li style="float:left;margin-right:5px;">
                <?php echo label_for('task_user', 'Assigned to'), select_tag('task_user', options_for_select($users, $task->getSingleUser('uuid'))) ?>
            </li>
            <li style="float:left;margin-right:5px;">
                <?php echo label_for('priority', 'Task Priority'), select_task_priority('priority', $task->getPriority()) ?><br />
            </li>
          </ul>
          <ul style="clear:both;">
            <li style="float:left;margin-right:5px;">
                <?php echo label_for('begin', 'Task Begins Date'), object_input_date_tag($task, 'getBegin', array('rich' => 'true')) ?><br />
            </li>
            <li style="float:left;margin-right:5px;">
                <?php echo label_for('finish', 'Task Finish Date'), object_input_date_tag($task, 'getFinish', array('rich' => 'true')) ?><br />
            </li>
            <li style="float:left;margin-right:5px;padding-top:20px;">
                <?php echo checkbox_tag('status', sfConfig::get('app_task_status_completed'), $task->getStatus()), label_for('status', 'Task Completed', array('style' => 'display:inline;')) ?><br />
            </li>
          </ul>
          <div style="clear:left;padding:3px;">
            <?php echo label_for('description', 'Description of Task'), object_textarea_tag($task, 'getDescription', array('rows' => '3', 'style' => 'clear:left;')) ?>
          </div>
          <?php //echo textarea_tag('task_tags', '', array('rows' => '3')) ?>
        </fieldset>
        <?php echo submit_tag(__('Save task changes')) ?>
      </form>
    </div>
  </div>
</div>
