<?php
// auto-generated by sfPropelCrud
// date: 2008/04/07 23:35:01
?>
<h1>tasks</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Uuid</th>
  <th>Project</th>
  <th>Owner</th>
  <th>Name</th>
  <th>Slug</th>
  <th>Description</th>
  <th>Begin</th>
  <th>Finish</th>
  <th>Status</th>
  <th>Version</th>
  <th>Deleted at</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($tasks as $task): ?>
<tr>
    <td><?php echo link_to($task->getId(), 'tasks/show?id='.$task->getId()) ?></td>
      <td><?php echo $task->getUuid() ?></td>
      <td><?php echo $task->getProjectId() ?></td>
      <td><?php echo $task->getOwnerId() ?></td>
      <td><?php echo $task->getName() ?></td>
      <td><?php echo $task->getSlug() ?></td>
      <td><?php echo $task->getDescription() ?></td>
      <td><?php echo $task->getBegin() ?></td>
      <td><?php echo $task->getFinish() ?></td>
      <td><?php echo $task->getStatus() ?></td>
      <td><?php echo $task->getVersion() ?></td>
      <td><?php echo $task->getDeletedAt() ?></td>
      <td><?php echo $task->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'tasks/create') ?>
