<?php
// auto-generated by sfPropelCrud
// date: 2008/04/07 23:35:01
?>

<?php use_helper('Date', 'Global') ?>
<table>
<tbody>
<th><?php echo ucwords(__('project')) ?>: </th>
<td><?php echo $task->getProject() ?></td>
</tr>
<tr>
<th><?php echo ucwords(__('name')) ?>: </th>
<td><?php echo $task->getName() ?></td>
</tr>
<tr>
<th></th>
<td>Set by <?php echo $task->getOwner() ?></td>
</tr>
<tr>
<th><?php echo ucwords(__('description')) ?>: </th>
<td><?php echo nl2br($task->getDescription()) ?></td>
</tr>
<tr>
<th><?php echo ucwords(__('time')) ?>: </th>
<td><?php echo format_date($task->getBegin()) ?> - <?php echo format_date($task->getFinish()) ?></td>
</tr>
<tr>
<th><?php echo ucwords(__('status')) ?>: </th>
<td><?php echo $task->getStatusInWords() ?></td>
</tr>
<tr>
  <th><?php echo ucwords(__('assigned to')) ?>:</th>
  <td>
    <?php foreach($task->getUsers() as $user) { echo $user->getSfGuardUser()->getProfile().'<br />'; } ?>
</tbody>
</table>
<?php echo link_to_function(ucwords(__('comments for %1%', array('%1%' => $task->getName()))), visual_effect('toggle_blind', 'comments-holder', array('duration' => 0.5)), array('class' => 'titlebar-clickable project-titlebar')); ?>
<div id='comments-holder' class='collapsed' style='padding:4px;'>
  <h3><?php echo ucwords(__('comments')) ?></h3>
  <?php
    include_component('sfComment', 'commentList', array('object' => $task));
    include_component('sfComment', 'commentForm', array('object' => $task));
  ?>
</div>
<?php echo link_to(ucwords(__('edit')), 'tasks/edit?id='.$task->getId()) ?>
&nbsp;<?php echo link_to(ucwords(__('list')), 'tasks/list') ?>
