<?php
// auto-generated by sfPropelCrud
// date: 2008/02/18 03:11:47
?>
<?php use_helper('Global', 'Object', 'Form', 'Javascript') ?>

<?php echo nav_tabs('messages', 'compose'); ?>

    <?php if ($sf_request->hasErrors()): ?>
      <div>
        <span>Something seems to be wrong with your message. Please correct these errors and resend it:</span>
        <ul>
        <?php foreach($sf_request->getErrors() as $name => $error): ?>
          <li><?php echo $error ?></li>
        <?php endforeach; ?>
        </ul>
      </div>
    <?php endif; ?>


<div class="blue-shadow"><div class="blue-title blue-content">Compose a Message</div></div>
<div class="blue-shadow">
  <div class="blue-content">
    <?php echo form_tag('messages/send') ?>
      <?php echo object_input_hidden_tag($message, 'getParentId') ?>
      <div class="message-view-single" style="border: medium none;">
        <?php echo link_to(image_tag($sf_user->getProfile()->getThumbnail(), array('class' => 'sender-pic')), 'user/show?user='.$sf_user->getProfile()->getUuid()) ?>
        <ul>
          <li>
            <?php echo ucwords(__('to')) ?>:<br />      
            <?php echo ucwords(__('subject')) ?>:
          </li>
          <li>
            <?php
              if ($message->getRecipientId())
              {  
                echo '<em>('.$message->getSfGuardUserRelatedByRecipientId()->getProfile()->getFullName().')</em><br />'.input_hidden_tag('user_recipient', $message->getSfGuardUserRelatedByRecipientId()->getProfile()->getFullName());
              }
              else
              {
                echo input_auto_complete_tag('user_recipient','','user/autoMessageComplete?field=recipient','autocomplete=false','use_style=true').'<br />';
              }
            ?>
            <?php echo object_input_tag($message, 'getSubject', array('style' => 'width:100%;'))?>
          </li>
        </ul>
        <hr class="clear" />
        <?php echo object_textarea_tag($message, 'getBody', array (
        'style' => 'width:100%;',
        'rows' => '10',
      )) ?>
        <?php echo submit_tag(ucwords(__('send')), array('class' => 'pswipebutton')) ?>
      </div>
    </form>
  </div>
</div>