<?php
// auto-generated by sfPropelCrud
// date: 2008/02/18 20:39:10
?>
<h1>message</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Sender</th>
  <th>Recipient</th>
  <th>Subject</th>
  <th>Body</th>
  <th>Html body</th>
  <th>Read at</th>
  <th>Parent</th>
  <th>Message type</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($messages as $message): ?>
<tr>
    <td><?php echo link_to($message->getId(), 'message/show?id='.$message->getId()) ?></td>
      <td><?php echo $message->getSenderId() ?></td>
      <td><?php echo $message->getRecipientId() ?></td>
      <td><?php echo $message->getSubject() ?></td>
      <td><?php echo $message->getBody() ?></td>
      <td><?php echo $message->getHtmlBody() ?></td>
      <td><?php echo $message->getReadAt() ?></td>
      <td><?php echo $message->getParentId() ?></td>
      <td><?php echo $message->getMessageType() ?></td>
      <td><?php echo $message->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'message/create') ?>
