<?php
// auto-generated by sfPropelCrud
// date: 2008/04/21 22:32:09
?>
    <table style="width:100%;">
        <thead>
            <tr>
                <td>Files</td>
                <td>Size</td>
                <td>Uploaded</td>
            </tr>
        </thead>
        <tbody>
            <?php $counter = 2; $direction = 1;?>
            <?php for ($i = 0; $i < 25; $i++): ?>
            <?php if ($counter == 3 || $counter == 1) $direction = -1 * $direction; ?>
            <?php $counter = $counter + (1 * $direction) ?>
                <tr class="row-<?php echo $counter % 3?>">
                    <td><?php echo link_to('updated_stuff_2009_'.$counter.'.zip', '#') ?></td>
                    <td>1.25 GB</td>
                    <td><?php echo format_date(time()) ?> by <?php echo link_to('Sean Grove', '#') ?></td>
                </tr>
            <?php endfor; ?>
        </tbody>
    </table>
