<?php
// auto-generated by sfPropelCrud
// date: 2008/04/21 22:32:09
?>
<?php use_helper('Object') ?>

<h1>CREATE</h1>

<?php echo form_tag('files/insert','multipart=true') ?>

<?php echo input_hidden_tag('entity',$sf_request->getParameter('entity')) ?>
<?php echo input_hidden_tag('entity_id',$sf_request->getParameter('entity_id')) ?>
<?php echo input_hidden_tag('referer',$sf_request->getReferer()) ?>
<table>
<tbody>

<tr>
  <th>File:</th>
  <td><?php echo input_file_tag('file') ?></td>
</tr>


<tr>
  <th>File Title:</th>
  <td><?php echo object_input_tag($file, 'getTitle', array (
  'size' => 30,
)) ?></td>
</tr>

<tr>
  <th>Description of File:</th>
  <td><?php echo object_textarea_tag($file, 'getDescription', array (
  'size' => '30x4',
)) ?></td>
</tr>

</tbody>
</table>

<hr />
<?php echo submit_tag('Upload file') ?>
</form>


