<?php use_helper('Date', 'FormatSize') ?>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/21 22:32:09
?>
<div class="resource-manager-panel2">
    <table style="width:100%;">
        <thead>
            <tr>
                <td>Files</td>
                <td>Size</td>
                <td>Uploaded</td>
            </tr>
        </thead>
        <tbody>
            <?php $counter = 2; $direction = 1;?>
            <?php foreach($files as $file): ?>
            <?php if ($counter == 3 || $counter == 1) $direction = -1 * $direction; ?>
            <?php $counter = $counter + (1 * $direction) ?>
                <tr class="row-<?php echo $counter % 3?>">
                    <td><a href="/cothink/web/<?php echo sfConfig::get('sf_upload_dir_name').'/files/'.urlencode($file->getRealName()) ?>"><?php echo $file->getName() ?></a></td>
                    <td><?php echo format_size($file->getSize()) ?></td>
                    <td><?php echo format_date(time()) ?> by
                    <?php if ($file->getUploadedBy() != null)
                    {
                        echo link_to($file->getsfGuardUser()->getProfile()->getFullName(), 'user/show?user='.$file->getsfGuardUser()->getProfile()->getUuid());
                    }
                    else
                    {
                        echo "anonymous";
                    } ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
