<?php
// auto-generated by sfPropelCrud
// date: 2008/04/21 22:32:09
?>
<?php use_helper('Object') ?>

<h1>Upload Image</h1>

<?php echo form_tag('@upload_photo','multipart=true') ?>

<?php echo input_hidden_tag('referer',$sf_request->getReferer()) ?>
<?php echo input_hidden_tag('entity',$sf_request->getParameter('entity')) ?>
<?php echo input_hidden_tag('entity_id',$sf_request->getParameter('entity_id')) ?>

<table>
<tbody>

<tr>
  <th><?php echo label_for('file', __('Image')) ?><?php if ($sf_request->hasError('file')) ?>:<?php echo '<div class="form-error">'.$sf_request->getError('file').'</div>' ?></th>
  <td><?php echo input_file_tag('file') ?></td>
</tr>


<tr>
  <th><?php echo label_for('title', __('Image Title')) ?>:</th>
  <td><?php echo object_input_tag($photo, 'getTitle', array (
  'size' => 30,
)) ?></td>
</tr>

<tr>
  <th><?php echo label_for('description', __('Image Description')) ?>:</th>
  <td><?php echo object_textarea_tag($photo, 'getDescription', array (
  'size' => '30x4',
)) ?></td>
</tr>

</tbody>
</table>
<?php echo $sf_user->getAttribute('referer') ?>
<hr />
<?php echo submit_tag(__('Upload Image')) ?>
</form>


