<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:48:34
?>
<?php use_helper('Object') ?>

<?php echo form_tag('campus/update') ?>

<?php echo object_input_hidden_tag($campus, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Uuid*:</th>
  <td><?php echo object_input_tag($campus, 'getUuid', array (
  'size' => 36,
)) ?></td>
</tr>
<tr>
  <th>Name*:</th>
  <td><?php echo object_input_tag($campus, 'getName', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Address:</th>
  <td><?php echo object_input_tag($campus, 'getAddress', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>City:</th>
  <td><?php echo object_input_tag($campus, 'getCity', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>State:</th>
  <td><?php echo object_input_tag($campus, 'getState', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Zip:</th>
  <td><?php echo object_input_tag($campus, 'getZip', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Url:</th>
  <td><?php echo object_input_tag($campus, 'getUrl', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Phone:</th>
  <td><?php echo object_input_tag($campus, 'getPhone', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Email*:</th>
  <td><?php echo object_input_tag($campus, 'getEmail', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Slug*:</th>
  <td><?php echo object_input_tag($campus, 'getSlug', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Version:</th>
  <td><?php echo object_input_tag($campus, 'getVersion', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Deleted at:</th>
  <td><?php echo object_input_date_tag($campus, 'getDeletedAt', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($campus->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'campus/delete?id='.$campus->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'campus/show?id='.$campus->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'campus/list') ?>
<?php endif; ?>
</form>
