<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:48:34
?>
<h1><?php echo ucwords(__('school')) ?></h1>

<table>
<thead>
<tr>
  <th><?php echo ucwords(__('school')) ?></th>
  <th><?php echo ucwords(__('about %2%', array('%2%' => __('school')))) ?></th>
</tr>
</thead>
<tbody>
<?php foreach ($campuss as $campus): ?>
  <tr>
      <td><?php echo link_to($campus->getName(), 'campus/show?slug='.$campus->getSlug()) ?></td>
      <td><?php echo $campus->getAboutBrief() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to (ucwords(__('create')), 'campus/create') ?>
