<?php
// auto-generated by sfPropelCrud
// date: 2008/04/04 15:24:10
?>
<?php

/**
 * user actions.
 *
 * @package    cothink
 * @subpackage user
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class homeComponents extends sfComponents
{
  public function executeDidYouKnow()
  {
    $this->didYouKnow = DidYouKnowPeer::getRandom();
  } 

  public function executeDidYouKnowText()
  {
    $this->didYouKnow = DidYouKnowPeer::getRandom();
  }
  
  /**
   * Executes TodoSidebar action
   *
   */
  public function executeTodoSidebar()
  {
    if ($this->getUser()->isAuthenticated()) {
      $this->todos = $this->getUser()->getProfile()->getTodos();
      $this->tasks = $this->todos['tasks'];
      $this->todos = $this->todos['todos'];
      return sfView::SUCCESS;
    }
    
    return sfView::NONE;
  }

  /**
   * Executes featuredProject action
   *
   */
  public function executeFeaturedProject()
  {
    $this->featured = FeaturedProjectPeer::retrieveRandom();
    if ($this->featured != null) {
      $this->project = $this->featured->getProject();
    }
  }
  
  /**
   * Executes signUpForm action
   *
   */
  public function executeSignUpForm()
  {
    $this->departments = DepartmentPeer::retrieveAlphabetical();
  }
}
